/**
 * ScouterAI — Hebrew settlement → standardized English region code
 *
 * Region codes: center | south | north | jerusalem | eilat | sharon | haifa_krayot | arava
 *
 * Geography:
 *   haifa_krayot — Haifa metro & Krayot suburbs
 *   north        — Galilee, Golan, Western Galilee, Jezreel Valley (north of Hadera, excl. Haifa metro)
 *   sharon       — Coastal Sharon plain (Netanya–Hadera) & inland Sharon
 *   center       — Gush Dan, Shfela, Modi'in corridor, Lod–Ramla–Rehovot
 *   jerusalem    — Jerusalem metro & Judean/Samarian hill country
 *   south        — Negev & southern coastal plain (Gedera southward, excl. Eilat/Arava)
 *   eilat        — Eilat city
 *   arava        — Arava valley & southern Dead Sea basin
 *
 * Entries: 1951
 */

module.exports = {
  "אבו בלאל": "center",
  "אבו גווייעד )שבט(": "south",
  "אבו גוש": "jerusalem",
  "אבו געדה": "center",
  "אבו דיס": "jerusalem",
  "אבו חמרה": "center",
  "אבו טוילה (": "center",
  "אבו סנאן": "center",
  "אבו סריחאן )שבט(": "south",
  "אבו עבדון )שבט(": "south",
  "אבו עמאר )שבט(": "south",
  "אבו עמרה )שבט(": "south",
  "אבו קורינאת )שבט(": "south",
  "אבו קרינאת )יישוב(": "center",
  "אבו קש": "center",
  "אבו רובייעה )שבט(": "south",
  "אבו רוקייק )שבט(": "south",
  "אבו שחידם": "center",
  "אבו תלול": "center",
  "אבטין": "center",
  "אבטליון": "center",
  "אביאל": "center",
  "אביבים": "center",
  "אביגדור": "center",
  "אביחיל": "center",
  "אביטל": "center",
  "אביעזר": "center",
  "אבירים": "center",
  "אבן יהודה": "sharon",
  "אבן מנחם": "center",
  "אבן ספיר": "center",
  "אבן שמואל": "center",
  "אבני איתן": "center",
  "אבני חפץ": "center",
  "אבנת": "center",
  "אבשלום": "center",
  "אבתאן": "center",
  "אג'נסניא": "center",
  "אדורה": "center",
  "אדירים": "center",
  "אדמית": "center",
  "אדנה": "center",
  "אדרת": "center",
  "אהלו": "center",
  "אודים": "center",
  "אודלה": "center",
  "אודם": "center",
  "אוהד": "center",
  "אום אל תות": "center",
  "אום אל-פחם": "center",
  "אום אל-קוטוף": "center",
  "אום בטין": "center",
  "אומן": "center",
  "אומץ": "center",
  "אופקים": "south",
  "אוצרין": "center",
  "אור הגנוז": "center",
  "אור הנר": "center",
  "אור יהודה": "center",
  "אור עקיבא": "sharon",
  "אורה": "center",
  "אורות": "center",
  "אורטל": "north",
  "אורים": "center",
  "אורנים": "center",
  "אורנית": "sharon",
  "אושה": "center",
  "אזור": "center",
  "אחווה": "center",
  "אחוזם": "south",
  "אחוזת ברק": "center",
  "אחיהוד": "center",
  "אחיטוב": "sharon",
  "אחיסמך": "center",
  "אחיעזר": "center",
  "אטרש )שבט(": "south",
  "איבים": "south",
  "אייל": "center",
  "איילת השחר": "center",
  "אילון": "center",
  "אילות": "arava",
  "אילניה": "center",
  "אילת": "eilat",
  "איתמר": "jerusalem",
  "איתן": "south",
  "איתנים": "jerusalem",
  "אכסאל": "center",
  "אכתאבא": "center",
  "אל בירה": "jerusalem",
  "אל סייד": "center",
  "אל עריש": "center",
  "אל-עזי": "south",
  "אל-עריאן": "south",
  "אל-רום": "north",
  "אלומה": "south",
  "אלומות": "center",
  "אלון הגליל": "center",
  "אלון מורה": "center",
  "אלון שבות": "jerusalem",
  "אלוני אבא": "center",
  "אלוני הבשן": "center",
  "אלוני יצחק": "center",
  "אלונים": "center",
  "אלי סיני": "center",
  "אלי-עד": "north",
  "אליכין": "sharon",
  "אליפז": "arava",
  "אליפלט": "center",
  "אליקים": "center",
  "אלישיב": "center",
  "אלישמע": "center",
  "אלמגור": "center",
  "אלמוג": "center",
  "אלעד": "center",
  "אלעזר": "jerusalem",
  "אלפי מנשה": "sharon",
  "אלקוש": "center",
  "אלקנה": "sharon",
  "אם א טלע": "center",
  "אם אל גנם": "center",
  "אם חשיבה": "center",
  "אם סלמונה": "center",
  "אם עלאס": "center",
  "אם עסלה": "center",
  "אם צפא": "center",
  "אם קוצרי": "center",
  "אמאתין": "center",
  "אמונים": "center",
  "אמירים": "center",
  "אמנון": "center",
  "אמציה": "south",
  "אמריש": "center",
  "אניעם": "north",
  "אסד )שבט(": "south",
  "אסכאכא": "center",
  "אספר": "center",
  "אעבלין": "center",
  "אעצם )שבט(": "south",
  "אפיניש )שבט(": "south",
  "אפיק": "center",
  "אפיקים": "center",
  "אפעל בית אב": "center",
  "אפעל מרכז ס": "center",
  "אפק": "center",
  "אפרתה": "jerusalem",
  "ארבל": "center",
  "ארגמן": "center",
  "ארז": "center",
  "ארטאס": "center",
  "אריאל": "sharon",
  "ארסוף": "sharon",
  "ארתאח": "center",
  "אשבול": "south",
  "אשבל": "south",
  "אשדוד": "south",
  "אשדות יעקב )איחוד(": "center",
  "אשדות יעקב )מאוחד(": "center",
  "אשחר": "center",
  "אשכולות": "south",
  "אשל הנשיא": "south",
  "אשלים": "south",
  "אשקלון": "south",
  "אשרת": "center",
  "אשתאול": "jerusalem",
  "אתגר": "center",
  "אתר מצדה": "arava",
  "באגה": "center",
  "באקה": "center",
  "באקה אל שרק": "center",
  "באקה אל-גרביה": "center",
  "באר אורה": "arava",
  "באר גנים": "sharon",
  "באר טוביה": "center",
  "באר יעקב": "center",
  "באר מילכה": "arava",
  "באר שבע": "south",
  "בארות יצחק": "center",
  "בארותיים": "sharon",
  "בארי": "south",
  "בגדד": "center",
  "בדו": "center",
  "בדולח": "center",
  "בדיא": "center",
  "בדרס": "center",
  "בוגה": "center",
  "בוסתן הגליל": "north",
  "בועיינה-נוגידאת": "center",
  "בוקעאתא": "north",
  "בורגתה": "center",
  "בורהאם": "center",
  "בורין": "center",
  "בורקה": "center",
  "בזאריה": "center",
  "בחן": "south",
  "בטחה": "south",
  "ביאדה": "center",
  "בידא": "center",
  "ביוכי": "center",
  "ביצרון": "center",
  "ביר א נצב": "jerusalem",
  "ביר א סכה": "jerusalem",
  "ביר אבו סוי": "jerusalem",
  "ביר אבו צוי": "jerusalem",
  "ביר אל חסי": "jerusalem",
  "ביר אל מלחה": "jerusalem",
  "ביר אל מעין": "jerusalem",
  "ביר אל עבד": "jerusalem",
  "ביר אל-מכסור": "jerusalem",
  "ביר אלמיין": "jerusalem",
  "ביר ג'אלא": "jerusalem",
  "ביר הדאג": "jerusalem",
  "ביר הליל": "jerusalem",
  "ביר זית": "jerusalem",
  "ביר חסנה": "jerusalem",
  "ביר לחפאן": "jerusalem",
  "ביר מלאקי": "jerusalem",
  "ביר מער": "jerusalem",
  "ביר נבאלא": "jerusalem",
  "ביר נצב": "jerusalem",
  "ביר סדרי": "jerusalem",
  "ביר שיח חמי": "jerusalem",
  "ביר תל": "jerusalem",
  "בירה חברון": "south",
  "ביריה": "north",
  "בית אג'זא": "jerusalem",
  "בית אולא": "jerusalem",
  "בית אורן": "jerusalem",
  "בית איבא": "jerusalem",
  "בית אכסא": "jerusalem",
  "בית אל": "jerusalem",
  "בית אל ב": "jerusalem",
  "בית אללו": "jerusalem",
  "בית אלעזרי": "jerusalem",
  "בית אלפא": "jerusalem",
  "בית אמין": "jerusalem",
  "בית אמר": "jerusalem",
  "בית אמרין": "jerusalem",
  "בית אענאן": "jerusalem",
  "בית ארוש פו": "jerusalem",
  "בית ארוש תח": "jerusalem",
  "בית אריה": "sharon",
  "בית ברל": "sharon",
  "בית ג'אלא": "south",
  "בית גוברין": "south",
  "בית גמאל": "jerusalem",
  "בית גמליאל": "center",
  "בית גן": "center",
  "בית דגן": "center",
  "בית דקו": "jerusalem",
  "בית הגדי": "jerusalem",
  "בית הלוי": "center",
  "בית הלל": "jerusalem",
  "בית העמק": "north",
  "בית הערבה": "arava",
  "בית השיטה": "jerusalem",
  "בית וזן": "jerusalem",
  "בית זיד": "jerusalem",
  "בית זית": "jerusalem",
  "בית זרע": "jerusalem",
  "בית חורון": "jerusalem",
  "בית חירות": "jerusalem",
  "בית חלקיה": "center",
  "בית חנון": "south",
  "בית חנינא": "jerusalem",
  "בית חנן": "center",
  "בית חנניה": "center",
  "בית חשמונאי": "center",
  "בית יהושע": "sharon",
  "בית יוסף": "jerusalem",
  "בית ינאי": "sharon",
  "בית יצחק-שער חפר": "sharon",
  "בית כאחל גמ": "jerusalem",
  "בית לאהיה": "south",
  "בית לחם": "jerusalem",
  "בית לחם הגלילית": "north",
  "בית ליד": "sharon",
  "בית לקיא": "jerusalem",
  "בית מאיר": "jerusalem",
  "בית מחסיר": "jerusalem",
  "בית מרסם": "jerusalem",
  "בית נחמיה": "center",
  "בית ניר": "center",
  "בית נקופה": "jerusalem",
  "בית סאחור": "jerusalem",
  "בית סוריכ": "jerusalem",
  "בית סירא": "jerusalem",
  "בית עוא": "jerusalem",
  "בית עובד": "center",
  "בית עוזיאל": "center",
  "בית עור אל": "jerusalem",
  "בית עזרא": "jerusalem",
  "בית עמרא": "jerusalem",
  "בית עריף": "center",
  "בית פג'אר": "jerusalem",
  "בית פוריכ": "jerusalem",
  "בית צבי": "center",
  "בית קאד דרו": "jerusalem",
  "בית קאד צפו": "jerusalem",
  "בית קמה": "south",
  "בית קשת": "jerusalem",
  "בית רבן": "jerusalem",
  "בית רימא": "jerusalem",
  "בית רימון": "center",
  "בית שאן": "north",
  "בית שמש": "jerusalem",
  "בית שערים": "jerusalem",
  "בית שקמה": "south",
  "ביתא א תחתא": "center",
  "ביתא פוקא": "center",
  "ביתוניא": "jerusalem",
  "ביתין": "jerusalem",
  "ביתן אהרן": "sharon",
  "ביתר עילית": "jerusalem",
  "בכורה": "south",
  "בלאטה": "south",
  "בלעא": "center",
  "בלעין": "center",
  "בלפוריה": "north",
  "בן זכאי": "center",
  "בן עמי": "north",
  "בן שמן )כפר נוער(": "center",
  "בן שמן )מושב(": "center",
  "בני ברק": "center",
  "בני דקלים": "south",
  "בני דרום": "south",
  "בני דרור": "sharon",
  "בני יהודה": "north",
  "בני נעים": "south",
  "בני נצרים": "south",
  "בני סוהילה": "south",
  "בני עטרות": "center",
  "בני עי\"ש": "center",
  "בני עצמון": "south",
  "בני ציון": "sharon",
  "בני ראם": "center",
  "בניה": "center",
  "בנימינה-גבעת עדה": "sharon",
  "בסמ\"ה": "center",
  "בסמת טבעון": "haifa_krayot",
  "בענה": "north",
  "בצרה": "center",
  "בצת": "north",
  "בקוע": "jerusalem",
  "בקעות": "north",
  "בר גיורא": "jerusalem",
  "בר יוחאי": "north",
  "ברג'": "center",
  "ברדלא": "center",
  "ברוקין": "sharon",
  "ברור חיל": "center",
  "ברוש": "north",
  "ברטעה": "center",
  "בריג": "north",
  "ברכה": "center",
  "ברכיה": "center",
  "ברעם": "north",
  "ברק": "center",
  "ברקא": "center",
  "ברקאי": "center",
  "ברקין": "sharon",
  "ברקן": "sharon",
  "ברקת": "center",
  "בת הדר": "sharon",
  "בת חן": "sharon",
  "בת חפר": "sharon",
  "בת חצור": "sharon",
  "בת ים": "center",
  "בת עין": "sharon",
  "בת שלמה": "sharon",
  "בתיר": "center",
  "ג'אלוד": "center",
  "ג'אניה": "center",
  "ג'ארושיה": "center",
  "ג'בע ג'נין": "north",
  "ג'בע רמאללה": "north",
  "ג'בעה": "jerusalem",
  "ג'דידה": "north",
  "ג'דירה": "north",
  "ג'וריש": "north",
  "ג'ורת אל שמ": "center",
  "ג'ז אבו רעד": "center",
  "ג'יב": "north",
  "ג'יביא": "center",
  "ג'יוס": "north",
  "ג'ית": "north",
  "ג'לבון": "north",
  "ג'לג'ליה": "north",
  "ג'לזון": "north",
  "ג'למה": "north",
  "ג'לקמוס": "center",
  "ג'מאלה": "center",
  "ג'מאעין": "center",
  "ג'ניד": "north",
  "ג'נין": "north",
  "ג'נצאפוט": "center",
  "ג'רבא": "north",
  "גאולי תימן": "center",
  "גאולים": "sharon",
  "גאליה": "center",
  "גבאליה": "center",
  "גבאליה העיר": "center",
  "גבולות": "south",
  "גבים": "south",
  "גבל אל ערף": "center",
  "גבל הלאל": "center",
  "גבל חמיר": "center",
  "גבל מגארה": "center",
  "גבע": "jerusalem",
  "גבע בנימין": "jerusalem",
  "גבע כרמל": "haifa_krayot",
  "גבעולים": "center",
  "גבעון החדשה": "jerusalem",
  "גבעות בר": "jerusalem",
  "גבעת אבני": "center",
  "גבעת אלה": "sharon",
  "גבעת ברנר": "center",
  "גבעת השלושה": "sharon",
  "גבעת זאב": "jerusalem",
  "גבעת ח\"ן": "sharon",
  "גבעת חיים )איחוד(": "sharon",
  "גבעת חיים )מאוחד(": "sharon",
  "גבעת יואב": "south",
  "גבעת יערים": "jerusalem",
  "גבעת ישעיהו": "jerusalem",
  "גבעת כ\"ח": "haifa_krayot",
  "גבעת ניל\"י": "sharon",
  "גבעת עדה": "sharon",
  "גבעת עוז": "center",
  "גבעת שמואל": "center",
  "גבעת שמש": "jerusalem",
  "גבעת שפירא": "sharon",
  "גבעתי": "south",
  "גבעתיים": "center",
  "גברעם": "center",
  "גבת": "north",
  "גדות": "north",
  "גדיד": "center",
  "גדידה": "center",
  "גדיידה-מכר": "center",
  "גדיש": "north",
  "גדעונה": "north",
  "גדרה": "center",
  "גולס": "center",
  "גונן": "north",
  "גורן": "north",
  "גורנות הגליל": "north",
  "גזית": "north",
  "גזר": "center",
  "גיאה": "center",
  "גיבתון": "center",
  "גיזו": "center",
  "גילון": "north",
  "גילת": "south",
  "גינוסר": "north",
  "גיניגר": "north",
  "גינתון": "center",
  "גיתה": "north",
  "גיתית": "north",
  "גלאון": "south",
  "גלגוליה": "center",
  "גלגל": "north",
  "גליל ים": "north",
  "גלעד )אבן יצחק(": "north",
  "גמזו": "center",
  "גן אור": "north",
  "גן הדרום": "south",
  "גן השומרון": "sharon",
  "גן חיים": "sharon",
  "גן יאשיה": "center",
  "גן יבנה": "center",
  "גן נר": "north",
  "גן שורק": "center",
  "גן שלמה": "sharon",
  "גן שמואל": "sharon",
  "גנאביב )שבט(": "south",
  "גנות": "sharon",
  "גנות הדר": "sharon",
  "גני הדר": "sharon",
  "גני טל": "sharon",
  "גני טל *": "sharon",
  "גני יהודה": "center",
  "גני יוחנן": "center",
  "גני מודיעין": "center",
  "גני עם": "center",
  "גני תקווה": "center",
  "גנים": "center",
  "גסר א-זרקא": "sharon",
  "געש": "sharon",
  "געתון": "north",
  "גפן": "jerusalem",
  "גפנא": "center",
  "גקילה": "center",
  "גרופית": "arava",
  "גריעה": "south",
  "גש )גוש חלב(": "center",
  "גשור": "north",
  "גשר": "north",
  "גשר הזיו": "north",
  "גת": "center",
  "גת )קיבוץ(": "center",
  "גת בגליל": "north",
  "גת רימון": "center",
  "דאהריה": "south",
  "דאלית אל-כרמל": "haifa_krayot",
  "דבורה": "north",
  "דבוריה": "north",
  "דבירה": "south",
  "דברת": "north",
  "דגניה א": "north",
  "דגניה ב": "north",
  "דהב": "center",
  "דהישה": "south",
  "דהר חלת אל": "center",
  "דוב\"ב": "center",
  "דוגית": "center",
  "דולב": "jerusalem",
  "דומא חברון": "south",
  "דומא שכם": "north",
  "דור": "sharon",
  "דורא": "center",
  "דורא אל קרע": "center",
  "דורות": "south",
  "דחי": "center",
  "דחית בריד": "center",
  "דיוכ": "center",
  "דייר חנא": "north",
  "דייר ראפאת": "center",
  "דימונה": "south",
  "דיר א שמס": "jerusalem",
  "דיר אבו דעי": "north",
  "דיר אבו משע": "north",
  "דיר אבזיע": "jerusalem",
  "דיר אל בלח": "south",
  "דיר אל גצון": "north",
  "דיר אל חטב": "north",
  "דיר אל סודא": "north",
  "דיר אל עסל": "north",
  "דיר אל-אסד": "north",
  "דיר אסתיא": "north",
  "דיר בלוט": "north",
  "דיר גזאלה": "north",
  "דיר גסאנה": "north",
  "דיר גריר": "north",
  "דיר דבואן": "north",
  "דיר נזאם": "north",
  "דיר עמאר": "north",
  "דיר קדיס": "north",
  "דיר רזאח": "north",
  "דיר שרף": "north",
  "דישון": "north",
  "דליה": "north",
  "דלתון": "north",
  "דמיידה": "center",
  "דן": "north",
  "דנאבה": "center",
  "דפידף": "center",
  "דפנה": "north",
  "דקל": "south",
  "דרב אל מליח": "center",
  "דריגאת": "center",
  "האון": "center",
  "האשמיה": "center",
  "הבונים": "sharon",
  "הגושרים": "north",
  "הדר עם": "north",
  "הוד השרון": "sharon",
  "הודיה": "south",
  "הודיות": "south",
  "הוואשלה )שבט(": "south",
  "הוזייל )שבט(": "south",
  "הושעיה": "north",
  "הזורע": "north",
  "הזורעים": "north",
  "החותרים": "sharon",
  "היוגב": "north",
  "הילה": "north",
  "המעפיל": "north",
  "הסוללים": "north",
  "העוגן": "north",
  "הר אדר": "jerusalem",
  "הר גילה": "jerusalem",
  "הר עמשא": "jerusalem",
  "הראל": "jerusalem",
  "הרדוף": "north",
  "הרצליה": "sharon",
  "הררית": "north",
  "ואדי אל אחמ": "jerusalem",
  "ואדי אל ביד": "jerusalem",
  "ואדי אל וער": "jerusalem",
  "ואדי אל ערא": "jerusalem",
  "ואדי אל ערי": "jerusalem",
  "ואדי אסלה": "jerusalem",
  "ואדי ברקין": "jerusalem",
  "ואדי גרנדל": "jerusalem",
  "ואדי חמר": "jerusalem",
  "ואדי מבעוק": "jerusalem",
  "ואדי מחאש": "jerusalem",
  "ואדי נצב": "jerusalem",
  "ואדי נצריין": "jerusalem",
  "ואדי סעאל": "jerusalem",
  "ואדי קיד": "jerusalem",
  "ואדי קריה": "jerusalem",
  "ואדי רהבה": "jerusalem",
  "ואדי רחבה": "jerusalem",
  "ואדי רינה": "jerusalem",
  "ואדי תמן": "jerusalem",
  "ואדי תר": "jerusalem",
  "ואדיאל עמר": "center",
  "ואסט נויבע": "center",
  "ורד יריחו": "arava",
  "ורדון": "center",
  "זאויה ג'נין": "north",
  "זאויה טול כ": "center",
  "זבאבדה": "north",
  "זבארגה )שבט(": "south",
  "זבדה": "center",
  "זבדיאל": "center",
  "זבובה": "center",
  "זבידאת": "north",
  "זואתה": "center",
  "זוהר": "south",
  "זוואידה": "center",
  "זיף": "center",
  "זיקים": "south",
  "זיתא": "north",
  "זיתא ג'מעין": "center",
  "זיתונה": "center",
  "זיתן": "center",
  "זכרון יעקב": "sharon",
  "זכריה": "jerusalem",
  "זלפה": "center",
  "זמר": "sharon",
  "זמרת": "south",
  "זנוח": "jerusalem",
  "זעתרה": "jerusalem",
  "זרועה": "south",
  "זרזיר": "north",
  "זרחיה": "center",
  "חאן יונס": "south",
  "חאן יונס הע": "south",
  "חאראס": "center",
  "חארס": "north",
  "חבילה": "center",
  "חבלה": "center",
  "חבצלת השרון": "sharon",
  "חבר": "north",
  "חברון": "south",
  "חגאגרה": "north",
  "חגה": "center",
  "חגור": "sharon",
  "חגי": "south",
  "חגילה": "south",
  "חגלה": "jerusalem",
  "חד-נס": "north",
  "חדב": "center",
  "חדיד": "center",
  "חדר": "center",
  "חדרה": "sharon",
  "חואלד": "center",
  "חואלד )שבט(": "south",
  "חוארה": "center",
  "חוגייראת )דהרה(": "center",
  "חולדה": "center",
  "חולון": "center",
  "חולית": "south",
  "חולתה": "center",
  "חומש": "center",
  "חוסאן": "north",
  "חוסן": "north",
  "חוסנייה": "center",
  "חופית": "sharon",
  "חוקוק": "center",
  "חורה": "south",
  "חורסה": "center",
  "חורפיש": "north",
  "חורשים": "center",
  "חות שלם": "center",
  "חזאעה": "center",
  "חזון": "center",
  "חזמא": "center",
  "חיבת ציון": "center",
  "חיננית": "sharon",
  "חיפה": "haifa_krayot",
  "חירות": "sharon",
  "חלוץ": "south",
  "חלחול": "south",
  "חלמיש": "center",
  "חלף": "center",
  "חלץ": "south",
  "חלת אל פולה": "center",
  "חמאם": "center",
  "חמד": "jerusalem",
  "חמדיה": "center",
  "חמדת": "center",
  "חמרה": "center",
  "חניאל": "sharon",
  "חניתה": "north",
  "חנתון": "jerusalem",
  "חסכה": "south",
  "חספין": "north",
  "חפץ חיים": "center",
  "חפצי-בה": "center",
  "חצב": "center",
  "חצבה": "arava",
  "חצור הגלילית": "north",
  "חצור-אשדוד": "south",
  "חצר בארותיים": "sharon",
  "חצרות חולדה": "sharon",
  "חצרות חפר": "sharon",
  "חצרות יסף": "sharon",
  "חצרות כ\"ח": "sharon",
  "חצרים": "south",
  "חרב לאת": "center",
  "חרבת אבו חמ": "jerusalem",
  "חרבת אבו נג": "jerusalem",
  "חרבת אבו סל": "jerusalem",
  "חרבת אבו פל": "jerusalem",
  "חרבת אום אל": "jerusalem",
  "חרבת אל אקר": "jerusalem",
  "חרבת אל אשק": "jerusalem",
  "חרבת אל דיר": "jerusalem",
  "חרבת אל דלב": "jerusalem",
  "חרבת אל הגר": "jerusalem",
  "חרבת אל חדב": "jerusalem",
  "חרבת אל חפי": "jerusalem",
  "חרבת אל חרז": "jerusalem",
  "חרבת אל טבק": "jerusalem",
  "חרבת אל כום": "jerusalem",
  "חרבת אל לוז": "jerusalem",
  "חרבת אל מגו": "jerusalem",
  "חרבת אל מגנ": "jerusalem",
  "חרבת אל מדו": "jerusalem",
  "חרבת אל מטל": "jerusalem",
  "חרבת אל מנש": "jerusalem",
  "חרבת אל מעצ": "jerusalem",
  "חרבת אל מרג": "jerusalem",
  "חרבת אל נבי": "jerusalem",
  "חרבת אל נג": "jerusalem",
  "חרבת אל סכה": "jerusalem",
  "חרבת אל עדס": "jerusalem",
  "חרבת אל עוג": "jerusalem",
  "חרבת אל עלק": "jerusalem",
  "חרבת אל עקר": "jerusalem",
  "חרבת אל ערו": "jerusalem",
  "חרבת אל צרי": "jerusalem",
  "חרבת אל קצו": "jerusalem",
  "חרבת אל שיח": "jerusalem",
  "חרבת בית חס": "jerusalem",
  "חרבת בית ענ": "jerusalem",
  "חרבת בית תע": "jerusalem",
  "חרבת בריזעה": "jerusalem",
  "חרבת גאדור": "jerusalem",
  "חרבת גהזם": "jerusalem",
  "חרבת גיב א": "jerusalem",
  "חרבת גראד": "jerusalem",
  "חרבת דיר צא": "jerusalem",
  "חרבת ואדי א": "jerusalem",
  "חרבת ודח": "jerusalem",
  "חרבת זאהר": "jerusalem",
  "חרבת זיתא": "jerusalem",
  "חרבת חדיר": "jerusalem",
  "חרבת טויל": "jerusalem",
  "חרבת כזון": "jerusalem",
  "חרבת כנעאן": "jerusalem",
  "חרבת כרמה": "jerusalem",
  "חרבת מורק": "jerusalem",
  "חרבת מעין": "jerusalem",
  "חרבת נבי צא": "jerusalem",
  "חרבת סמיא": "jerusalem",
  "חרבת עאבא": "jerusalem",
  "חרבת עוד": "jerusalem",
  "חרבת עילת ע": "jerusalem",
  "חרבת עסלה": "jerusalem",
  "חרבת פקיקס": "jerusalem",
  "חרבת צאפא": "jerusalem",
  "חרבת ציר": "jerusalem",
  "חרבת קיס": "jerusalem",
  "חרבת ראס אל": "jerusalem",
  "חרבת ראס עט": "jerusalem",
  "חרבת רקעה": "jerusalem",
  "חרבת שויכה": "jerusalem",
  "חרבתא": "jerusalem",
  "חרבתא אל מצ": "jerusalem",
  "חרובה כולל": "center",
  "חרוצים": "sharon",
  "חריש -קציר": "sharon",
  "חרמלה": "south",
  "חרמש": "north",
  "חרסה": "center",
  "חרשים": "north",
  "חשמונאים": "jerusalem",
  "טבעון": "haifa_krayot",
  "טבריה": "north",
  "טואני": "center",
  "טובא-זנגריה": "north",
  "טובאס": "north",
  "טויל אל אמי": "center",
  "טול כרם": "north",
  "טורה אל גרב": "center",
  "טורעאן": "north",
  "טיבה ג'נין": "north",
  "טיבה רמאללה": "north",
  "טייבה": "sharon",
  "טייבה )בעמק(": "north",
  "טירה": "sharon",
  "טירת יהודה": "center",
  "טירת כרמל": "haifa_krayot",
  "טירת צבי": "north",
  "טל שחר": "center",
  "טל-אל": "center",
  "טלוזה": "center",
  "טללים": "center",
  "טלמון": "jerusalem",
  "טמון": "center",
  "טמרה": "center",
  "טמרה )יזרעאל(": "north",
  "טנא": "center",
  "טפחות": "center",
  "טראמה": "center",
  "יאטה": "center",
  "יאמון": "north",
  "יאנוח": "north",
  "יאנוח-גת": "north",
  "יאנון": "center",
  "יאסוף": "north",
  "יאציד": "center",
  "יבול": "south",
  "יבנאל": "center",
  "יבנה": "center",
  "יברוד": "north",
  "יגור": "center",
  "יגל": "center",
  "יד בנימין": "center",
  "יד השמונה": "jerusalem",
  "יד חנה": "center",
  "יד מרדכי": "south",
  "יד נתן": "south",
  "יד רמב\"ם": "jerusalem",
  "ידידה": "jerusalem",
  "יהוד-מונוסון": "center",
  "יהל": "arava",
  "יובל": "north",
  "יובלים": "north",
  "יודפת": "north",
  "יונתן": "north",
  "יושיביה": "center",
  "יזרעאל": "north",
  "יזרעם": "north",
  "יחיעם": "north",
  "יטבתה": "arava",
  "ייט\"ב": "center",
  "יכיני": "south",
  "ימא": "center",
  "ינוב": "center",
  "ינון": "center",
  "יסוד המעלה": "north",
  "יסודות": "center",
  "יסעור": "north",
  "יעבד": "north",
  "יעד": "north",
  "יעל": "north",
  "יעף": "center",
  "יערה": "north",
  "יפיע": "north",
  "יפית": "north",
  "יפעת": "north",
  "יפתח": "north",
  "יצהר": "north",
  "יציץ": "center",
  "יקום": "center",
  "יקיר": "north",
  "יקנעם )מושבה(": "north",
  "יקנעם עילית": "north",
  "יראון": "north",
  "ירדנה": "north",
  "ירוחם": "south",
  "ירושלים": "jerusalem",
  "ירחיב": "center",
  "יריחו": "arava",
  "ירכא": "north",
  "ירקונה": "center",
  "ישע": "center",
  "ישעי": "center",
  "ישרש": "center",
  "יתד": "south",
  "יתיר": "south",
  "יתמא": "center",
  "כאבול": "north",
  "כאוכב אבו אל-היגא": "north",
  "כברי": "north",
  "כדורי": "north",
  "כדים": "north",
  "כדיתה": "north",
  "כובר": "center",
  "כוכב השחר": "jerusalem",
  "כוכב יאיר": "sharon",
  "כוכב יעקב": "jerusalem",
  "כוכב מיכאל": "south",
  "כונתילא": "center",
  "כור": "center",
  "כורזים": "north",
  "כזיה אל רטר": "center",
  "כחל": "north",
  "כחלה": "north",
  "כיסופים": "south",
  "כישור": "north",
  "כליל": "north",
  "כלנית": "north",
  "כמאנה": "north",
  "כמהין": "south",
  "כמון": "north",
  "כנות": "south",
  "כנף": "north",
  "כנרת )מושבה(": "north",
  "כנרת )קבוצה(": "north",
  "כסיפה": "south",
  "כסלון": "jerusalem",
  "כסרא": "north",
  "כסרא-סמיע": "north",
  "כעביה שבט": "south",
  "כעביה-טבאש-חגאגרה": "north",
  "כפיר": "north",
  "כפירת": "north",
  "כפל חארת": "center",
  "כפר אביב": "jerusalem",
  "כפר אדומים": "jerusalem",
  "כפר אוריה": "jerusalem",
  "כפר אזר": "jerusalem",
  "כפר אחים": "jerusalem",
  "כפר אל דיכ": "jerusalem",
  "כפר אל לבד": "jerusalem",
  "כפר ביאליק": "haifa_krayot",
  "כפר ביל\"ו": "jerusalem",
  "כפר בלום": "north",
  "כפר בן נון": "jerusalem",
  "כפר ברא": "center",
  "כפר ברוך": "jerusalem",
  "כפר גדעון": "jerusalem",
  "כפר גלים": "haifa_krayot",
  "כפר גליקסון": "jerusalem",
  "כפר גלעדי": "north",
  "כפר גמאל": "north",
  "כפר דאן": "north",
  "כפר דניאל": "jerusalem",
  "כפר דרום": "south",
  "כפר האורנים": "jerusalem",
  "כפר החורש": "jerusalem",
  "כפר המכבי": "jerusalem",
  "כפר הנגיד": "jerusalem",
  "כפר הנוער הדתי": "jerusalem",
  "כפר הנשיא": "jerusalem",
  "כפר הס": "jerusalem",
  "כפר הרא\"ה": "jerusalem",
  "כפר הרי\"ף": "jerusalem",
  "כפר ויתקין": "sharon",
  "כפר ורבורג": "north",
  "כפר ורדים": "sharon",
  "כפר זוהרים": "jerusalem",
  "כפר זיבאד": "north",
  "כפר זיתים": "jerusalem",
  "כפר חב\"ד": "center",
  "כפר חושן": "sharon",
  "כפר חיטים": "sharon",
  "כפר חיים": "sharon",
  "כפר חנניה": "sharon",
  "כפר חסידים א": "jerusalem",
  "כפר חסידים ב": "jerusalem",
  "כפר חרוב": "jerusalem",
  "כפר טרומן": "jerusalem",
  "כפר יאסיף": "center",
  "כפר ידידיה": "sharon",
  "כפר יהושע": "sharon",
  "כפר יונה": "sharon",
  "כפר יחזקאל": "sharon",
  "כפר יעבץ": "sharon",
  "כפר כמא": "north",
  "כפר כנא": "north",
  "כפר לאקף": "jerusalem",
  "כפר מאלכ": "jerusalem",
  "כפר מונש": "jerusalem",
  "כפר מימון": "south",
  "כפר מל\"ל": "sharon",
  "כפר מנדא": "north",
  "כפר מנחם": "jerusalem",
  "כפר מסריק": "haifa_krayot",
  "כפר מצר": "jerusalem",
  "כפר מרדכי": "jerusalem",
  "כפר נטר": "sharon",
  "כפר נעמה": "sharon",
  "כפר סאלד": "jerusalem",
  "כפר סבא": "sharon",
  "כפר סילבר": "sharon",
  "כפר סירקין": "sharon",
  "כפר סמיע": "north",
  "כפר עבודה": "sharon",
  "כפר עבוש": "north",
  "כפר עזה": "south",
  "כפר עזיז": "center",
  "כפר עין": "center",
  "כפר עציון": "jerusalem",
  "כפר עקב": "jerusalem",
  "כפר פינס": "sharon",
  "כפר צור": "center",
  "כפר קאסם": "center",
  "כפר קדום": "north",
  "כפר קוד": "center",
  "כפר קיש": "center",
  "כפר קליל": "center",
  "כפר קרע": "center",
  "כפר ראעי": "center",
  "כפר ראש הנקרה": "sharon",
  "כפר רוזנואלד )זרעית(": "jerusalem",
  "כפר רופין": "north",
  "כפר רות": "jerusalem",
  "כפר רמאן": "center",
  "כפר שמאי": "jerusalem",
  "כפר שמואל": "jerusalem",
  "כפר שמריהו": "jerusalem",
  "כפר תבור": "north",
  "כפר תלת": "center",
  "כפר תפוח": "jerusalem",
  "כרזה": "center",
  "כרי דשא": "center",
  "כרכום": "center",
  "כרם אבו מצל": "center",
  "כרם אבו שרי": "center",
  "כרם בן זמרה": "north",
  "כרם בן שמן": "center",
  "כרם יבנה )ישיבה(": "center",
  "כרם מהר\"ל": "north",
  "כרם שלום": "south",
  "כרמי יוסף": "center",
  "כרמי צור": "center",
  "כרמיאל": "north",
  "כרמיה": "south",
  "כרמים": "south",
  "כרמל": "north",
  "לבון": "north",
  "לביא": "north",
  "לבן": "center",
  "לבן שרקיה": "center",
  "לבנים": "north",
  "להב": "north",
  "להבות הבשן": "north",
  "להבות חביבה": "north",
  "להבים": "south",
  "לוד": "center",
  "לוזית": "jerusalem",
  "לוחמי הגיטאות": "north",
  "לוטם": "south",
  "לוטן": "south",
  "לימן": "north",
  "לכיש": "south",
  "לפיד": "center",
  "לפידות": "north",
  "לקיה": "south",
  "מאדמא": "center",
  "מאור": "north",
  "מאיר שפיה": "center",
  "מאסורה": "center",
  "מאקורה": "center",
  "מבוא ביתר": "jerusalem",
  "מבוא דותן": "jerusalem",
  "מבוא חורון": "jerusalem",
  "מבוא חמה": "center",
  "מבוא מודיעים": "center",
  "מבואות ים": "center",
  "מבועים": "center",
  "מבטחים": "south",
  "מבקיעים": "jerusalem",
  "מבשרת ציון": "jerusalem",
  "מגאזי": "center",
  "מגאר": "north",
  "מגד": "north",
  "מגד אל-כרום": "center",
  "מגדים": "north",
  "מגדל": "north",
  "מגדל בני פא": "center",
  "מגדל העמק": "north",
  "מגדל עוז": "north",
  "מגדל שמס": "north",
  "מגדלים": "north",
  "מגידו": "north",
  "מגיר ג'נין": "center",
  "מגיר רמאללה": "center",
  "מגל": "center",
  "מגן": "south",
  "מגן שאול": "center",
  "מגשימים": "center",
  "מדיה": "center",
  "מדפונה": "center",
  "מדרך עוז": "center",
  "מדרשת בן גוריון": "south",
  "מדרשת רופין": "center",
  "מודיעין עילית": "jerusalem",
  "מודיעין-מכבים-רעות": "center",
  "מולדה": "center",
  "מולדת": "center",
  "מוצא עילית": "jerusalem",
  "מוצא תחתית": "jerusalem",
  "מוצמוץ": "center",
  "מוקייבלה": "center",
  "מורג": "north",
  "מורן": "north",
  "מורשת": "north",
  "מושב אליאב": "south",
  "מזאר": "center",
  "מזארע אל נו": "center",
  "מזור": "center",
  "מזכרת בתיה": "center",
  "מזרע": "north",
  "מזרעה": "north",
  "מזרעה אל קב": "center",
  "מזרעה אל שר": "center",
  "מחולה": "center",
  "מחים אל פאר": "center",
  "מחים קלנדיה": "center",
  "מחמאס": "center",
  "מחנה גבעת ח": "center",
  "מחנה הילה": "center",
  "מחנה טלי": "center",
  "מחנה יבור": "center",
  "מחנה יהודית": "center",
  "מחנה יוכבד": "center",
  "מחנה יפה": "center",
  "מחנה יתיר": "south",
  "מחנה מרים": "center",
  "מחנה עדי": "center",
  "מחנה תל נוף": "center",
  "מחניים": "north",
  "מחסיה": "jerusalem",
  "מחשיב": "center",
  "מטולה": "north",
  "מטע": "north",
  "מי עמי": "north",
  "מידאן": "center",
  "מיטב": "north",
  "מייסר": "center",
  "מיצר": "north",
  "מירב": "north",
  "מירון": "north",
  "מישר": "south",
  "מיתלה": "center",
  "מיתלון": "center",
  "מיתר": "south",
  "מכבים": "center",
  "מכורה": "north",
  "מכחול": "center",
  "מכמורת": "center",
  "מכמנים": "north",
  "מכסורה": "center",
  "מכר": "center",
  "מלאה": "center",
  "מלילות": "south",
  "מלכיה": "south",
  "מלכישוע": "center",
  "מנבטח": "center",
  "מנוחה": "south",
  "מנוף": "north",
  "מנות": "north",
  "מנחמיה": "north",
  "מנרה": "north",
  "מנשית זבדה": "center",
  "מסד": "north",
  "מסדה": "south",
  "מסחה": "north",
  "מסילות": "north",
  "מסילת ציון": "jerusalem",
  "מסלול": "south",
  "מסליה": "center",
  "מסעדה": "center",
  "מסעודין אל-עזאזמה": "center",
  "מעאויה": "center",
  "מעברות": "sharon",
  "מעגלים": "south",
  "מעגן": "center",
  "מעגן מיכאל": "sharon",
  "מעוז חיים": "north",
  "מעון": "south",
  "מעונה": "north",
  "מעוף": "center",
  "מעיליא": "north",
  "מעין ברוך": "north",
  "מעין צבי": "sharon",
  "מעלה אדומים": "jerusalem",
  "מעלה אפרים": "sharon",
  "מעלה גלבוע": "north",
  "מעלה גמלא": "north",
  "מעלה החמישה": "jerusalem",
  "מעלה לבונה": "jerusalem",
  "מעלה מכמש": "jerusalem",
  "מעלה עירון": "north",
  "מעלה עמוס": "jerusalem",
  "מעלה שומרון": "sharon",
  "מעלות-תרשיחא": "north",
  "מעני אבו חא": "center",
  "מענית": "north",
  "מעסכר אל ער": "center",
  "מעש": "center",
  "מפלסים": "south",
  "מצבח": "center",
  "מצדות יהודה": "jerusalem",
  "מצובה": "north",
  "מצליח": "center",
  "מצפה": "north",
  "מצפה אבי\"ב": "north",
  "מצפה אילן": "center",
  "מצפה יריחו": "arava",
  "מצפה נטופה": "north",
  "מצפה רמון": "south",
  "מצפה שלם": "arava",
  "מצפק": "center",
  "מצר": "north",
  "מקדבה(עגילה": "center",
  "מקווה ישראל": "center",
  "מראח אל בקר": "center",
  "מראח רבאח": "center",
  "מרג נעגה": "center",
  "מרגה": "center",
  "מרגליות": "north",
  "מרדה": "center",
  "מרום גולן": "north",
  "מרחב עם": "north",
  "מרחביה )מושב(": "north",
  "מרחביה )קיבוץ(": "north",
  "מרכה": "center",
  "מרכז שפירא": "center",
  "משאבי שדה": "center",
  "משאיח סעדיה": "center",
  "משגב דב": "center",
  "משגב עם": "north",
  "משהד": "north",
  "משואה": "north",
  "משואות יצחק": "south",
  "משירפה": "south",
  "משכיות": "south",
  "משמר איילון": "center",
  "משמר דוד": "center",
  "משמר הירדן": "north",
  "משמר הנגב": "south",
  "משמר העמק": "north",
  "משמר השבעה": "center",
  "משמר השרון": "sharon",
  "משמרות": "sharon",
  "משמרת": "sharon",
  "משען": "south",
  "משרוע מוסא": "center",
  "מתמתני": "center",
  "מתן": "sharon",
  "מתת": "north",
  "מתתיהו": "center",
  "נאות גולן": "north",
  "נאות הכיכר": "arava",
  "נאות מרדכי": "center",
  "נאות סמדר": "arava",
  "נאעורה": "center",
  "נאקורה": "center",
  "נבטים": "south",
  "נבי צאלח": "center",
  "נבי צמויל": "center",
  "נביעות": "center",
  "נבק": "center",
  "נגבה": "south",
  "נגוהות": "south",
  "נגידאת": "center",
  "נגילה": "center",
  "נהורה": "south",
  "נהלל": "north",
  "נהריה": "north",
  "נוב": "north",
  "נובא": "center",
  "נוגה": "south",
  "נוה": "center",
  "נוה אפרים": "center",
  "נוה דקלים": "center",
  "נווה אבות": "jerusalem",
  "נווה אור": "north",
  "נווה אטי\"ב": "north",
  "נווה אילן": "jerusalem",
  "נווה איתן": "jerusalem",
  "נווה דניאל": "jerusalem",
  "נווה זוהר": "south",
  "נווה זיו": "north",
  "נווה חריף": "arava",
  "נווה ים": "sharon",
  "נווה ימין": "haifa_krayot",
  "נווה ירק": "center",
  "נווה מבטח": "center",
  "נווה מיכאל": "jerusalem",
  "נווה שלום": "jerusalem",
  "נויעמה": "center",
  "נומיס": "center",
  "נועם": "south",
  "נוף איילון": "center",
  "נופים": "north",
  "נופית": "north",
  "נופך": "center",
  "נוקדים": "jerusalem",
  "נור אל שמס": "center",
  "נורדיה": "center",
  "נורית": "center",
  "נזלה אל גרב": "center",
  "נזלה אל וסט": "center",
  "נזלה אל שרק": "center",
  "נזלת אבו נא": "center",
  "נזלת זיד": "center",
  "נזלת עיסא": "center",
  "נחאלין": "jerusalem",
  "נחושה": "jerusalem",
  "נחל אדורה": "center",
  "נחל אלישע": "center",
  "נחל אמתי": "center",
  "נחל בתרונות": "center",
  "נחל גבעות": "center",
  "נחל גנת": "center",
  "נחל יעלון": "center",
  "נחל מול נבו": "center",
  "נחל מרוה": "center",
  "נחל נחושתן": "center",
  "נחל נמרוד": "center",
  "נחל נצרים": "center",
  "נחל עוז": "center",
  "נחל עירית": "center",
  "נחל צורף": "center",
  "נחל צרי": "center",
  "נחל שיאון": "center",
  "נחל)חפגה(": "center",
  "נחלה": "jerusalem",
  "נחליאל": "jerusalem",
  "נחלים": "jerusalem",
  "נחלת יהודה": "center",
  "נחם": "jerusalem",
  "נחף": "north",
  "נחשולים": "sharon",
  "נחשון": "jerusalem",
  "נחשונים": "jerusalem",
  "נטועה": "south",
  "נטור": "north",
  "נטעים": "south",
  "נטף": "jerusalem",
  "ניין": "north",
  "ניל\"י": "jerusalem",
  "ניסנית": "north",
  "ניצן": "south",
  "ניצן ב": "south",
  "ניצנה )קהילת חינוך(": "center",
  "ניצני סיני": "arava",
  "ניצני עוז": "south",
  "ניצנים": "south",
  "ניר אליהו": "center",
  "ניר בנים": "center",
  "ניר גלים": "center",
  "ניר דוד )תל עמל(": "north",
  "ניר ח\"ן": "south",
  "ניר יפה": "north",
  "ניר יצחק": "south",
  "ניר ישראל": "south",
  "ניר משה": "center",
  "ניר עוז": "south",
  "ניר עם": "south",
  "ניר עציון": "center",
  "ניר עקיבא": "south",
  "ניר צבי": "center",
  "נירים": "south",
  "נירית": "sharon",
  "נירן": "north",
  "נמל תעופה בן גוריון": "center",
  "נס הרים": "jerusalem",
  "נס עמים": "north",
  "נס ציונה": "center",
  "נעורים": "north",
  "נעלה": "jerusalem",
  "נעלין": "jerusalem",
  "נעמ\"ה": "jerusalem",
  "נען": "center",
  "נצאצרה )שבט(": "south",
  "נצאריה": "center",
  "נציראת": "center",
  "נצף גביל": "center",
  "נצר חזני": "center",
  "נצר חזני *": "center",
  "נצר סרני": "center",
  "נצרת": "north",
  "נצרת עילית": "north",
  "נקא שעבאני": "center",
  "נשר": "haifa_krayot",
  "נתיב הגדוד": "north",
  "נתיב הל\"ה": "jerusalem",
  "נתיב העשרה": "center",
  "נתיב השיירה": "center",
  "נתיבות": "south",
  "נתניה": "sharon",
  "סאגור": "center",
  "סאויה": "center",
  "סאלם": "center",
  "סאסא": "north",
  "סביון": "center",
  "סבסטיה": "north",
  "סגולה": "south",
  "סדום": "arava",
  "סואחרה": "center",
  "סואעד )חמרייה(": "center",
  "סואעד )כמאנה( (שבט(": "south",
  "סולם": "center",
  "סוסיה": "south",
  "סופה": "south",
  "סחנין": "north",
  "סייד )שבט(": "south",
  "סייפה": "center",
  "סילת אל דאה": "center",
  "סילת אל חאר": "center",
  "סיריס": "center",
  "סלואד": "center",
  "סלמאנה": "center",
  "סלמה": "center",
  "סלעית": "center",
  "סלפית": "center",
  "סמוע": "center",
  "סמר": "center",
  "סנג'ל": "center",
  "סנטה קטרינה": "jerusalem",
  "סניריה": "center",
  "סנסנה": "center",
  "סעד": "south",
  "סעיר": "center",
  "סער": "center",
  "ספארין": "center",
  "ספיר": "arava",
  "סרדה": "center",
  "סתריה": "center",
  "עאבוד": "center",
  "עאנין": "center",
  "עארה": "center",
  "עארורה": "center",
  "עבאסן אל כב": "center",
  "עבאסן אל צע": "center",
  "עבדה": "center",
  "עבדון": "center",
  "עבוין": "center",
  "עבידיה": "center",
  "עברון": "center",
  "עג'ה": "center",
  "עגול": "center",
  "עגור": "jerusalem",
  "עגר": "center",
  "עדי": "north",
  "עדנים": "sharon",
  "עוזה": "center",
  "עוזייר": "center",
  "עולש": "center",
  "עומר": "south",
  "עופר": "north",
  "עופרה": "jerusalem",
  "עופרים": "center",
  "עוצם": "center",
  "עוקבי )בנו עוקבה(": "center",
  "עוריף": "center",
  "עורתא": "center",
  "עזבת א דרוב": "center",
  "עזה": "south",
  "עזוז": "center",
  "עזון": "center",
  "עזון עתמה": "center",
  "עזמוט": "center",
  "עזר": "north",
  "עזריאל": "center",
  "עזריה": "center",
  "עזריקם": "south",
  "עטאוונה )שבט(": "south",
  "עטאטרה": "center",
  "עטארה ג'נין": "center",
  "עטארה רמאלל": "center",
  "עטרת": "jerusalem",
  "עידן": "south",
  "עיזריה": "center",
  "עיילבון": "north",
  "עיינות": "center",
  "עילוט": "north",
  "עין א סהלה": "jerusalem",
  "עין איוב": "jerusalem",
  "עין איילה": "haifa_krayot",
  "עין אל אחדר": "jerusalem",
  "עין אל בידא": "jerusalem",
  "עין אל שלטא": "jerusalem",
  "עין אל-אסד": "jerusalem",
  "עין גב": "north",
  "עין גדי": "arava",
  "עין דור": "north",
  "עין דרויש": "jerusalem",
  "עין הבשור": "jerusalem",
  "עין הוד": "jerusalem",
  "עין החורש": "center",
  "עין המפרץ": "haifa_krayot",
  "עין הנצי\"ב": "north",
  "עין העמק": "north",
  "עין השופט": "north",
  "עין השלושה": "center",
  "עין ורד": "center",
  "עין זיוון": "north",
  "עין חוד": "north",
  "עין חצבה": "arava",
  "עין חרוד )איחוד(": "north",
  "עין חרוד )מאוחד(": "north",
  "עין יברוד": "jerusalem",
  "עין יהב": "arava",
  "עין יעקב": "jerusalem",
  "עין כרם-בי\"ס חקלאי": "jerusalem",
  "עין כרמל": "sharon",
  "עין מאהל": "north",
  "עין נקובא": "jerusalem",
  "עין סיניא": "north",
  "עין עירון": "north",
  "עין עריכ": "jerusalem",
  "עין צדר": "jerusalem",
  "עין צורים": "jerusalem",
  "עין קידכאת": "jerusalem",
  "עין קיניא": "jerusalem",
  "עין קנייא": "jerusalem",
  "עין ראפה": "jerusalem",
  "עין שמר": "sharon",
  "עין שריד": "center",
  "עין תמר": "arava",
  "עינאבוס": "center",
  "עינת": "center",
  "עיר אובות": "arava",
  "עכו": "north",
  "עלאר": "center",
  "עלומים": "south",
  "עלי": "jerusalem",
  "עלי זהב": "jerusalem",
  "עלמה": "north",
  "עלמון": "jerusalem",
  "עלקה": "center",
  "עמוקה": "jerusalem",
  "עמור": "center",
  "עמוריה": "center",
  "עמינדב": "jerusalem",
  "עמיעד": "north",
  "עמיעוז": "south",
  "עמיקם": "jerusalem",
  "עמיר": "north",
  "עמנואל": "jerusalem",
  "עמק חפר": "sharon",
  "עמקה": "jerusalem",
  "ענאב אל צגי": "center",
  "ענאתא": "jerusalem",
  "ענב": "jerusalem",
  "ענבתא": "jerusalem",
  "ענזה": "north",
  "עסאכרה": "jerusalem",
  "עסכר": "jerusalem",
  "עספיא": "north",
  "עפולה": "north",
  "עץ אפרים": "sharon",
  "עצירה אל קב": "center",
  "עצירה אלשמא": "center",
  "עצמון שגב": "jerusalem",
  "עקאבה": "center",
  "עקבת גבר": "center",
  "עקרבה": "center",
  "עראבה": "north",
  "עראמשה": "north",
  "עראמשה שבט": "north",
  "עראנה": "north",
  "עראק בורין": "north",
  "ערב אבו ציב": "center",
  "ערב אל חסינ": "center",
  "ערב אל נעים": "center",
  "ערבונה": "north",
  "ערד": "south",
  "ערוגות": "center",
  "ערערה": "north",
  "ערערה-בנגב": "south",
  "ערקה": "north",
  "עשרת": "center",
  "עתיל": "center",
  "עתלית": "north",
  "עתניאל": "jerusalem",
  "פארן": "arava",
  "פאת שדה": "center",
  "פדואל": "jerusalem",
  "פדויים": "jerusalem",
  "פדיה": "jerusalem",
  "פוגיה": "center",
  "פוור": "center",
  "פוריה - כפר עבודה": "north",
  "פוריה - נווה עובד": "north",
  "פוריה עילית": "north",
  "פוריידיס": "north",
  "פורת": "sharon",
  "פחמה": "center",
  "פטיש": "south",
  "פיראן": "center",
  "פלאמה": "center",
  "פלך": "north",
  "פלמחים": "south",
  "פנדק": "center",
  "פנדקומיה": "center",
  "פני חבר": "jerusalem",
  "פסגות": "jerusalem",
  "פסוטה": "center",
  "פעמי תש\"ז": "jerusalem",
  "פצאיל": "center",
  "פצאל": "center",
  "פקועה": "jerusalem",
  "פקיעין )בוקייעה(": "north",
  "פקיעין חדשה": "north",
  "פרדס חנה-כרכור": "sharon",
  "פרדסיה": "sharon",
  "פרוד": "center",
  "פרוש בית דג": "center",
  "פרזון": "north",
  "פרחה": "south",
  "פרי גן": "south",
  "פרנגה": "center",
  "פרעה אל גיפ": "center",
  "פרעון": "center",
  "פרעתה": "center",
  "פתח תקווה": "center",
  "פתחיה": "center",
  "צאלים": "arava",
  "צאנור": "center",
  "צאנע)שבט(": "south",
  "צביה": "center",
  "צבעון": "center",
  "צובה": "jerusalem",
  "צוחר": "south",
  "צופיה": "center",
  "צופים": "jerusalem",
  "צופית": "sharon",
  "צופר": "arava",
  "צוקי ים": "center",
  "צוקים": "south",
  "צור הדסה": "jerusalem",
  "צור יגאל": "center",
  "צור יצחק": "sharon",
  "צור משה": "sharon",
  "צור נתן": "sharon",
  "צוריאל": "north",
  "צוריף": "north",
  "צורית": "north",
  "צורן": "sharon",
  "צידא": "center",
  "ציפורי": "north",
  "ציר": "center",
  "צלפון": "jerusalem",
  "צנדלה": "center",
  "צפא": "center",
  "צפריה": "center",
  "צפרירים": "jerusalem",
  "צפת": "north",
  "צרה": "center",
  "צרופה": "jerusalem",
  "צרטא": "center",
  "צרעה": "jerusalem",
  "ק.מ. 45": "center",
  "קבאטיה": "center",
  "קבה": "center",
  "קבועה )שבט(": "south",
  "קבוצת יבנה": "center",
  "קביא": "center",
  "קביבה": "center",
  "קבלאן": "center",
  "קבר עמיר": "center",
  "קדומים": "sharon",
  "קדימה-צורן": "sharon",
  "קדמה": "sharon",
  "קדמת צבי": "north",
  "קדר": "jerusalem",
  "קדרון": "jerusalem",
  "קדרים": "north",
  "קודייראת א-": "center",
  "קוואעין )שבט(": "south",
  "קוממיות": "south",
  "קוצימה": "center",
  "קוצין": "center",
  "קורנית": "north",
  "קטורה": "arava",
  "קטיף": "south",
  "קטנה": "center",
  "קיסריה": "sharon",
  "קירה": "center",
  "קלחים": "south",
  "קליה": "arava",
  "קלנדיה": "jerusalem",
  "קלנסווה": "sharon",
  "קלע": "center",
  "קלקיליה": "jerusalem",
  "קפין": "center",
  "קציר": "north",
  "קצר א-סר": "center",
  "קצרה": "center",
  "קצרין": "north",
  "קראות בני ז": "center",
  "קראות בני ח": "center",
  "קרארה": "center",
  "קריות": "haifa_krayot",
  "קרית אונו": "center",
  "קרית ארבע": "jerusalem",
  "קרית אתא": "haifa_krayot",
  "קרית ביאליק": "haifa_krayot",
  "קרית גת": "south",
  "קרית חיים": "haifa_krayot",
  "קרית טבעון": "haifa_krayot",
  "קרית ים": "haifa_krayot",
  "קרית יערים": "jerusalem",
  "קרית יערים)מוסד(": "jerusalem",
  "קרית מוצקין": "haifa_krayot",
  "קרית מלאכי": "south",
  "קרית נטפים": "center",
  "קרית ענבים": "jerusalem",
  "קרית עקרון": "center",
  "קרית שלמה": "south",
  "קרית שמונה": "north",
  "קרני שומרון": "sharon",
  "קשת": "north",
  "ראבא": "center",
  "ראבוד": "center",
  "ראם": "center",
  "ראמה": "center",
  "ראמין": "center",
  "ראס": "north",
  "ראס אל נקב": "center",
  "ראס אל-עין": "center",
  "ראס כרכר": "center",
  "ראס נצראני": "center",
  "ראס סאלם": "center",
  "ראס סניסל": "center",
  "ראס עלי": "center",
  "ראפאת חברון": "south",
  "ראפאת טול כ": "north",
  "ראפאת רמאלל": "north",
  "ראש העין": "center",
  "ראש פינה": "north",
  "ראש צורים": "center",
  "ראשון לציון": "center",
  "רבבה": "center",
  "רבדים": "center",
  "רביבים": "south",
  "רביד": "center",
  "רבעה כולל ב": "center",
  "רגבה": "north",
  "רגבים": "north",
  "רהט": "south",
  "רוגיב": "center",
  "רווחה": "south",
  "רוויה": "center",
  "רוח מדבר": "south",
  "רוחמה": "south",
  "רומאנה": "north",
  "רומת הייב": "north",
  "רועי": "north",
  "רותם": "arava",
  "רחוב": "north",
  "רחובות": "center",
  "רחימה": "north",
  "ריחאניה": "north",
  "ריחיה": "south",
  "ריחן": "center",
  "ריינה": "north",
  "רימונים": "jerusalem",
  "רינתיה": "sharon",
  "ריסאן": "center",
  "רכום": "center",
  "רכסים": "north",
  "רם-און": "north",
  "רמאללה": "jerusalem",
  "רמאנה": "north",
  "רמון": "north",
  "רמות": "north",
  "רמות השבים": "center",
  "רמות מאיר": "center",
  "רמות מנשה": "sharon",
  "רמות נפתלי": "north",
  "רמלה": "center",
  "רמסה": "north",
  "רמת אפעל": "center",
  "רמת גן": "center",
  "רמת דוד": "center",
  "רמת הכובש": "center",
  "רמת השופט": "north",
  "רמת השרון": "center",
  "רמת חובב": "south",
  "רמת יוחנן": "haifa_krayot",
  "רמת ישי": "haifa_krayot",
  "רמת מגשימים": "center",
  "רמת פנקס": "center",
  "רמת צבי": "north",
  "רמת רזיאל": "jerusalem",
  "רמת רחל": "jerusalem",
  "רנן": "south",
  "רנתיס": "center",
  "רעים": "south",
  "רעננה": "sharon",
  "רפידה": "center",
  "רפידיה": "center",
  "רפיח": "south",
  "רפיח העיר": "south",
  "רפיח ים": "south",
  "רקפת": "north",
  "רשפון": "sharon",
  "רשפים": "north",
  "רתמים": "center",
  "שא-נור": "center",
  "שאטי": "center",
  "שאר ישוב": "north",
  "שבי ציון": "north",
  "שבי שומרון": "sharon",
  "שבלי - אום אל-גנם": "center",
  "שבע בארות": "center",
  "שבתין": "center",
  "שגב-שלום": "north",
  "שדה אילן": "north",
  "שדה אליהו": "north",
  "שדה אליעזר": "north",
  "שדה בוקר": "south",
  "שדה דוד": "center",
  "שדה ורבורג": "center",
  "שדה יואב": "south",
  "שדה יעקב": "north",
  "שדה יצחק": "center",
  "שדה משה": "center",
  "שדה נחום": "north",
  "שדה נחמיה": "north",
  "שדה ניצן": "south",
  "שדה עוזיהו": "south",
  "שדה צבי": "south",
  "שדות ים": "sharon",
  "שדות מיכה": "jerusalem",
  "שדי אברהם": "south",
  "שדי חמד": "center",
  "שדי תרומות": "south",
  "שדמה": "center",
  "שדמות דבורה": "north",
  "שדמות מחולה": "north",
  "שדרות": "south",
  "שואבה": "jerusalem",
  "שובה": "center",
  "שובל": "south",
  "שוהם": "center",
  "שויכה": "center",
  "שוכת א צופי": "center",
  "שומרה": "north",
  "שומריה": "south",
  "שופה": "south",
  "שוקדה": "south",
  "שורש": "jerusalem",
  "שורשים": "jerusalem",
  "שושנת העמקים": "north",
  "שזור": "north",
  "שחר": "south",
  "שחרות": "arava",
  "שיבולים": "south",
  "שיוח": "center",
  "שיח אחמד": "center",
  "שיח אחמד אל": "center",
  "שיח בריכ": "center",
  "שיח זויד": "center",
  "שיח חשש": "center",
  "שיח סלימאן": "center",
  "שיח סעיד": "center",
  "שיח עגלין": "center",
  "שיח עוד": "center",
  "שיטים": "arava",
  "שייח דנון": "center",
  "שילה": "jerusalem",
  "שילת": "jerusalem",
  "שכם": "north",
  "שכניה": "center",
  "שלאק וג'ורה": "center",
  "שלווה": "center",
  "שלווה במדבר": "south",
  "שלוחות": "north",
  "שלומי": "north",
  "שלומית": "north",
  "שליו": "arava",
  "שמיר": "north",
  "שמעה": "south",
  "שמרת": "north",
  "שמשית": "north",
  "שני": "center",
  "שניר": "north",
  "שעב": "north",
  "שעורים": "north",
  "שעל": "north",
  "שעלבים": "center",
  "שער אפרים": "sharon",
  "שער הגולן": "north",
  "שער העמקים": "north",
  "שער מנשה": "sharon",
  "שערי אברהם": "center",
  "שערי תקווה": "sharon",
  "שפיים": "sharon",
  "שפיר": "south",
  "שפר": "center",
  "שפרעם": "north",
  "שקבה": "center",
  "שקד": "center",
  "שקף": "center",
  "שרונה": "north",
  "שריגים )לי-און(": "center",
  "שריד": "center",
  "שרשרת": "north",
  "שתולה": "north",
  "שתולים": "center",
  "תאשור": "south",
  "תדהר": "south",
  "תובל": "north",
  "תומר": "north",
  "תושיה": "south",
  "תיאסיר": "center",
  "תימורים": "center",
  "תירוש": "jerusalem",
  "תל": "center",
  "תל א שמסיה": "center",
  "תל אבו שנאר": "center",
  "תל אביב - יפו": "center",
  "תל אל אחמר": "center",
  "תל אל בידא": "center",
  "תל יוסף": "center",
  "תל יצחק": "center",
  "תל מונד": "sharon",
  "תל עדשים": "north",
  "תל קציר": "north",
  "תל שבע": "south",
  "תל תאומים": "north",
  "תלם": "south",
  "תלמי אליהו": "arava",
  "תלמי אלעזר": "center",
  "תלמי ביל\"ו": "arava",
  "תלמי יוסף": "arava",
  "תלמי יחיאל": "arava",
  "תלמי יפה": "arava",
  "תלמים": "arava",
  "תלפית ג'נין": "north",
  "תלפית שכם": "north",
  "תמד": "center",
  "תמרת": "north",
  "תנובות": "center",
  "תעוז": "jerusalem",
  "תענך": "north",
  "תפוח": "jerusalem",
  "תפרח": "jerusalem",
  "תקומה": "jerusalem",
  "תקוע": "jerusalem",
  "תראבין א-צאנע )שבט(": "south",
  "תראבין א-צאנע)ישוב(": "center",
  "תרום": "center",
  "תרמוסעיא": "center",
  "תרפת אל קדר": "north",
  "תרקומיא": "north",
};
